import { game_config } from '$lib/game-config'

const SIL_LICENSE = 'SIL Open Font License'
const VIA_GOOGLE_FONTS = 'via Google Fonts'
const CC_BY_NC_SA_LICENSE = 'CC BY-NC-SA 4.0'
// Author of both WarGames recreation fonts (Title for credits, Terminal for the controls hint).
const MICHAEL_WALDEN = 'Michael Walden'
const CREATOR = 'Joshua Folkken'
const AI_ENGINEER = 'Claude Opus 4.8'

// Each staff entry renders as the role, the name, then two blank spacer lines. Generating
// the blocks from role lists (rather than spelling each out) keeps the roll DRY.
const STAFF_ROLES = [
	'CREATIVE DIRECTOR',
	'GAME DIRECTOR',
	'GAME DESIGNER',
	'PRODUCER',
	'WORLD ARCHITECT',
	'ART DIRECTOR',
	'SOUND DIRECTOR',
	'EXPERIENCE DESIGNER',
]

const ENGINEERING_ROLES = [
	'TECHNOLOGY DIRECTOR',
	'LEAD PROGRAMMER',
	'SYSTEMS ARCHITECT',
	'ENGINE PROGRAMMER',
	'UI PROGRAMMER',
	'AUDIO PROGRAMMER',
	'TEST ENGINEER',
	'QA ENGINEER',
	'REFACTORING LEAD',
	'CODE REVIEWER',
	'BUILD ENGINEER',
]

function role_block(role: string, name: string): Array<string> {
	return [role, name, '', '']
}

export const CREDITS_LINES = [
	game_config.GAME_NAME_UPPER,
	'CREDITS',
	'',
	'',
	'',
	'',
	'A JOSHUA FOLKKEN GAME',
	'',
	'',
	'',
	'',
	'SPONSORS',
	'',
	'',
	'Dejisapo',
	'',
	'Incognito',
	'',
	'Daisuke',
	'',
	'',
	'',
	'',
	'SPECIAL THANKS',
	'',
	'',
	'Unicorn',
	'aopuyodaihuku',
	'sakuramoti',
	'@DocSeventeenth',
	'@product_shokai',
	'Longinus',
	'fish',
	'Ejirou',
	'Satou',
	'Incognito',
	'@pirategamesdev',
	'@minotaursmx',
	'@akikawa922',
	'JUNKO',
	'Daisuke',
	'@SHIZUYA_1224',
	'@armeria_game',
	'',
	'',
	'',
	'',
	'GAME CONCEPT',
	'',
	'',
	`${game_config.GAME_NAME_DISPLAY} is inspired by the`,
	'1983 film WarGames',
	'directed by',
	'John Badham',
	'written by',
	'Lawrence Lasker',
	'and Walter F. Parkes',
	'',
	'',
	'',
	'',
	'BUILT WITH',
	'',
	'',
	'LANGUAGE',
	'TypeScript',
	'',
	'',
	'FRAMEWORK',
	'Svelte 5 (Runes)',
	'SvelteKit',
	'',
	'',
	'3D RENDERING',
	'Three.js',
	'Threlte',
	'',
	'',
	'STYLING',
	'Tailwind CSS v4',
	'',
	'',
	'BUILD TOOL',
	'Vite',
	'',
	'',
	'AUDIO',
	'Web Audio API',
	'Sound Effect by DRAGON-STUDIO',
	'from Pixabay',
	'',
	'',
	'DEPLOYMENT',
	'Cloudflare Workers via Wrangler',
	'',
	'',
	'',
	'',
	'FONTS',
	'',
	'',
	'WarGames Title',
	MICHAEL_WALDEN,
	CC_BY_NC_SA_LICENSE,
	'',
	'WarGames Terminal',
	MICHAEL_WALDEN,
	CC_BY_NC_SA_LICENSE,
	'',
	'Press Start 2P',
	'Cody "CodeMan38" Boisclair',
	SIL_LICENSE,
	VIA_GOOGLE_FONTS,
	'',
	'Orbitron',
	'Matt McInerney',
	SIL_LICENSE,
	VIA_GOOGLE_FONTS,
	'',
	'',
	'',
	'',
	'TESTING & TOOLING',
	'',
	'',
	'Vitest',
	'Playwright',
	'ESLint',
	'Prettier',
	'pnpm',
	'Lefthook',
	'@joshuafolkken/game-kit',
	'@joshuafolkken/kit',
	'',
	'',
	'',
	'',
	'OPEN SOURCE LIBRARIES',
	'',
	'',
	'svelte/svelte   MIT',
	'sveltejs/kit   MIT',
	'threlte/threlte   MIT',
	'mrdoob/three.js   MIT',
	'vitejs/vite   MIT',
	'vitest-dev/vitest   MIT',
	'microsoft/playwright   Apache 2.0',
	'tailwindlabs/tailwindcss   MIT',
	'',
	'',
	'',
	'',
	'STAFF',
	'',
	'',
	...STAFF_ROLES.flatMap((role) => role_block(role, CREATOR)),
	'- - -',
	'',
	'',
	...ENGINEERING_ROLES.flatMap((role) => role_block(role, AI_ENGINEER)),
	'',
	'',
	'ENGINEERED BY',
	'',
	'',
	AI_ENGINEER,
	'via Claude Code',
	'',
	'',
	'',
	'',
	'',
	'',
	'DIRECTED BY',
	'',
	'',
	CREATOR,
	'',
	'',
	'',
	'',
	'',
	'',
	'THANK YOU FOR PLAYING !!',
] as const

export const CREDITS_TEXT = CREDITS_LINES.join('\n')
export const CREDITS_LINE_COUNT = CREDITS_LINES.length
