version: '0.2'
import:
  - '@joshuafolkken/game-kit/cspell/game'
words:
  - waneccha
  - multicriteria
  - wargames
  - wopr
  - defcon
  - onpress
  - WASD
  - falken
  - theaterwide
  - biotoxic
  - negamax
  - luma
  - sfnt
  - scanlines
  - armeria
  - mnemecha
  - Badham
  - Lasker
  - Parkes
ignorePaths: []
