version: '0.2'
import:
  - '@joshuafolkken/game-kit/cspell/game'
  - ./cspell.project.yaml
dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
    addWords: true
dictionaries:
  - project-words
ignorePaths: []
